name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-2019, macos-latest ]
        ruby: [ '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', head ]
        include:

          # GH-988 must be merged to support ruby >= 3.3
          # - { os: windows-2019, ruby: mingw }

          # CRuby < 2.6 does not support macos-arm64, so these use amd64
          - { os: macos-13, ruby: "2.2" }
          - { os: macos-13, ruby: "2.3" }
          - { os: macos-13, ruby: "2.4" }
          - { os: macos-13, ruby: "2.5" }

        exclude:
          - { os: macos-latest, ruby: head }
          - { os: windows-2019, ruby: head }

          # GH-988 must be merged to support ruby >= 3.3
          - { ruby: 3.3 }
          - { ruby: head }

          # CRuby < 2.6 does not support macos-arm64, so these use amd64
          - { os: macos-latest, ruby: "2.2" }
          - { os: macos-latest, ruby: "2.3" }
          - { os: macos-latest, ruby: "2.4" }
          - { os: macos-latest, ruby: "2.5" }

          # Avoids the following error:
          #      Bundler 2 requires Ruby 2.3+, using Bundler 1 on Ruby <= 2.2
          #      /opt/hostedtoolcache/Ruby/2.2.10/x64/bin/gem install bundler -v ~> 1.0
          #      ERROR:  While executing gem ... (RuntimeError)
          #          Marshal.load reentered at marshal_load
          #
          # See https://github.com/ruby/setup-ruby/issues/496
          #
          # This works fine on ubuntu 20.04 and 24.04.
          - { os: ubuntu-22.04, ruby: '2.2' }

    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, openssl
        uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          mingw: _upgrade_ openssl

      - name: macOS disable firewall
        if: startsWith(matrix.os, 'macos')
        run: |
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
          sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate

      - name: bundle install
        run:  bundle install --jobs 4 --retry 3 --without=documentation

      - name: compile
        run:  bundle exec rake compile

      - name: test
        run:  bundle exec rake test
        env:
          CI: true
          TESTOPTS: -v --no-show-detail-immediately
